dbt_fusion_poc:
  target: dev
  outputs:
    dev:
      catalog: playground
      host: adb-5769108933149883.3.azuredatabricks.net
      http_path: /sql/1.0/warehouses/aebcaaff2f9457a3
      schema: dbt-fusion-poc
      threads: 10
      token: "{{ env_var('DBT_DATABRICKS_TOKEN') }}"
      type: databricks